### ISSUE TITLE
Плашка -- принудительно перенести данные

### ISSUE THREAD

**Issue by PackRuble** [sokolovromann/MyShopping#1]
Привет! Прежде всего, решительно благодарю за такое дивное приложение! Удивлён и польщён тем фактом, что были найдены силы, чтобы заредизайнить/обновить код. (хотя вы говорили, что приложение переписано с нуля 😅)
 
Собственно,
В настройках есть такая плашка и не очень понятен смысл её существования. Ну то есть, думаю что никто из пользователей не желал бы никуда "переноситься", если при этом будут удалены его данные. Быть может, есть возможность написать конвертер, чтобы перенести старые данные в новую систему? И этот пункт нам бы не понадобился тогда.

![Capture+_2023-06-04-08-31-23](https://github.com/sokolovromann/MyShopping/assets/88033450/38ac335f-564b-442c-b3d5-b4cb0d4c6c1a)

**Comment by sokolovromann** [comment]
Привет, спасибо за отзыв!

Возможно, я не корректно назвал или описал эту опцию. В новой версии (2.0.0) приложения новая база данных. Данные из старой базы автоматически переносятся в новую при первом открытии приложения. Но, если, что-то пойдёт не так и данные (частично или полностью) не переместятся, то можно нажать на эту плашку и все данные из старой базы попадут в новую. При этом все данные, созданные после обновления будут удалены, а старые (созданные в старой версии) останутся.

В следующем обновлении я исправлю описание.

**Comment by PackRuble** [comment]
ага, вот оно как :)
