### ISSUE TITLE
Reimplement old List of goods behaviour

### ISSUE THREAD

**Issue by stilgarwolf** [sokolovromann/MyShopping#2]
Used to be the best shopping app but removing the "List of goods" made it a mediocre one of the many.
When shopping a large number of items the autocompletes facility is almost unusable, as you had to remember tens of items to add.

An option to add items by checking them in autocompletes list, as old version did, will make your app one of the best again .

Best regards,

SW

**Comment by sokolovromann** [comment]
Thanks for feedback.

I'll return "List of goods" in the next version of the app.

**Comment by sokolovromann** [comment]
I returned the screen to the app. You need to go to Settings -> Purchases -> Display add from autocompletes button and activate the option.
The new version of the app will be available for download in Google Play in the near future.
